### ISSUE TITLE
Synthesis ignores silences in beginning and in ending

### ISSUE THREAD

**Issue by rhajit1001** [CSTR-Edinburgh/merlin#229]
I use state aligned labels created with the merlin tool.
When synthesising, the wav output ignores the silences in the beginning and in the end of the label, even if there are more than one silence. The enforce silence parameter in set to "True".

What could cause this kind of problem?

**Comment by ronanki** [comment]
Thank you for pointing out. 

We're overwriting the files at the synthesis time and hence caused this bug. The bug has been fixed now in the [latest commit](https://github.com/CSTR-Edinburgh/merlin/commit/257815108841f29700ba695d74b601539aeb49a9) by adding a new extension to the binary labels.

**Comment by rhajit1001** [comment]
Unfortunately, this commit doesn't help resolve the issue - it still happens in the latest version...

When we used phone-aligned labels this problem didn't happen - There was a silence at the beginning and the end of the wave file.

What else could possibly cause this problem?
