### ISSUE TITLE
Error using /prepare_labels_from_txt.sh & ./merlin_synthesis.sh

### ISSUE THREAD

**Issue by BiaWie** [CSTR-Edinburgh/merlin#255]
Hello there,

I'm trying to get merlin to talk to me (thus, generate new sentences) using the "standard" settings. 

Beforehand i tested _run_full_voice.sh,_ which was successfull and I received some wav-Files in _/slt_arctic_full/test_synthesis/wav_. 
Festival itself also works properly (I followed issue #96 for installation an now I can use (SayText "Here is my new senctence") and hear it read out loud). So I thought myself save..

Well, I created a directory ..._/test_synthesis/txt_ and in there a textfile named "_ThisIsATest.txt_" containing only the sentence "This is a test.".

As advised in issue #28  and tried to run _merlin_synthesis.sh_, (and in a next try only _prepare_labels_from_txt.sh_) but it doesn't work, instead I get following error message:

> creating a scheme file from text directory
> generating utts from scheme file
> *** Error in '...........merlin/tools/festival/bin/festival': free (): invalid next size (fast) : ......***

(followed by a lot of  "INFO configuration: Processes: ..." entries) and in the end

> IndexError: index 0 is out of bounds for axis 0 with size 0
> deleting intermediate synthesis files...
> synthesized audio files are in: .........../test_synthesis/wav
> 

Self-evidently there are no new files in there.  But anyway something DID happen: 
-it created two Files "ThisIsATest.lab" (one in promt-lab and one in gen-lab) which are both empty,
-a File "test_id_list.scp" (in test_synthesis) which contains my Filename "ThisIsATest" and 
-a File "new_test_sentences.scm", which says "(utt.save (.................. promt-utt/ThisIsATest.utt")

Any idea what I'm doing wrong? 
Did I miss anything during when installing festival? I'm puzzled.
Thanks in advance!

**Comment by seblemaguer** [comment]
Hello,

what is the version of gcc?

**Comment by gillesdegottex** [comment]
Hi guys,

I have the same issue here:
'''
creating a scheme file from text directory
generating utts from scheme file
*** Error in '...........merlin/tools/festival/bin/festival': free (): invalid next size (fast) : ......***
'''
gcc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0

Any idea @seblemaguer ? Festival should be compiled with a former version of gcc ?

**Comment by m-toman** [comment]
Is this related to the festival fixes in 2.5?
https://github.com/festvox/festival/blob/master/README.md

**Comment by seblemaguer** [comment]
@m-toman I think it is due to some flagging but I didn't investigate yet
@gillesdegottex that is what I am doing for now. After blizzard, I might see for that :D

**Comment by gillesdegottex** [comment]
Still 44 sentences crashing with gcc-6

**Comment by gillesdegottex** [comment]
Solved by compiling festival with gcc-4.8

**Comment by v-yunbin** [comment]
I met same error, how to compile festival with gcc-4.8?

**Comment by v-yunbin** [comment]
after compiling festival with gcc-4.8, same error still exists. someone have same case with me?

**Comment by yweweler** [comment]
Did you just recompile festival using gcc-4.8 or did you re-compile both speech_tools and festival?

I forced gcc to be gcc-4.8 and executed `compile_other_speech_tools.sh` again.
That seems to have solved it for me.

However, I executed the tests of both speech_tools and fetsival using `make test` in their base folders.
All tests from speech_tools pass as correct with gcc-4.8, when compiled with gcc-6 or gcc-7 most of the test fail.
When executing the tests of festival, even with gcc-4.8 half of the tests seem to fail.

**Comment by doctor-xiang** [comment]
hi,friend@v-yunbin! i met the same erro as you .so can you tell me how do you solve the problem.Thanks a lot!

**Comment by danny-fan** [comment]
Running into the same issue on Ubuntu 18.04.1 and wondering if there is any other tip to run merlin_synthesis.sh? 

Here are my steps: 
1. added txt folder under .../test_synthesis/
2. added a text file to the txt folder
3. ran prepare_labels_from_txt.sh
4. ran merlin_synthesis.sh
5. tried to run compile_other_speech_tools.sh to install festival under merlin dir
6. forced gcc to 4.8 
7. ran compile_other_speech_tools.sh but still got the following error log "Error installing speech tools"

**Comment by yyf** [comment]
Recompiled the tools using gcc 5.4, and was able to run ./run_full_voice.sh and ./merlin_synthesis.sh now.
